Repository madminer-tool/madminer, pull requests merged in 2021-06, with the labels that each got.

#460 Define read-the-docs config file
  .readthedocs.yml
Labels: bug

#461 Docs: replace recommonmark by MyST
  docs/conf.py
  docs/index.rst
  docs/modules.rst
  setup.py
Labels: internal

#462 Define docs GHA workflow
  .github/workflows/docs.yml
  docs/Makefile
  docs/conf.py
  docs/index.rst
  docs/installation.md
  docs/madminer.rst
  docs/references.md
  docs/usage.md
  madminer/fisherinformation/geometry.py
  madminer/ml/ensemble.py
Labels: enhancement

#463 Fix benchmark array dict_values
  madminer/analysis/dataanalyzer.py
Labels: bug

#458 Replace scikit-hep by vector pkg
  environment.yml
  madminer/__info__.py
  madminer/utils/interfaces/delphes_root.py
  madminer/utils/interfaces/lhe.py
  madminer/utils/particle.py
  setup.py
Labels: internal

#464 Fix GHA PyPi-publish version
  .github/workflows/publish.yml
Labels: bug

#465 Strip URLs out of the documentation
  README.md
  docs/installation.md
  docs/introduction.md
  docs/references.md
  docs/troubleshooting.md
  docs/usage.md
Labels: cosmetic, enhancement

#466 Python 3 syntax improvements
  madminer/analysis/dataanalyzer.py
  madminer/delphes/delphes_reader.py
  madminer/lhe/lhe_reader.py
  madminer/likelihood/histo.py
  madminer/limits/asymptotic_limits.py
  madminer/ml/base.py
  madminer/utils/ml/trainer.py
  madminer/utils/ml/utils.py
Labels: cosmetic

#468 Replace non-f-string concatenations
  README.md
  madminer/ml/base.py
  madminer/ml/ensemble.py
  madminer/utils/various.py
Labels: cosmetic

#469 Define custom dependabot.yml
  .github/dependabot.yml
Labels: enhancement

#467 Return arrays with training and validation losses in Ensemble methods + updating documentation
  madminer/ml/double_parameterized_ratio.py
  madminer/ml/ensemble.py
  madminer/ml/likelihood.py
  madminer/ml/parameterized_ratio.py
  madminer/ml/score.py
Labels: enhancement
